# Generated by Django 3.1.6 on 2021-02-17 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20210218_0228"),
    ]

    operations = [
        migrations.RemoveField(model_name="restaurant", name="menu",),
        migrations.AddField(
            model_name="menu",
            name="restaurant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.restaurant",
            ),
        ),
    ]
