# Generated by Django 3.1.6 on 2021-02-17 22:21

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20210218_0341"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="established",
            field=models.DateField(
                default=datetime.datetime(2021, 2, 18, 3, 51, 28, 49289)
            ),
        ),
    ]
