# Generated by Django 3.1.6 on 2021-02-17 22:27

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20210218_0351"),
    ]

    operations = [
        migrations.RemoveField(model_name="menu", name="cuisines",),
        migrations.AlterField(
            model_name="restaurant",
            name="established",
            field=models.DateField(
                default=datetime.datetime(2021, 2, 18, 3, 57, 46, 549063)
            ),
        ),
        migrations.CreateModel(
            name="Cuisine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("origin", models.CharField(max_length=255)),
                (
                    "popular_ingredients",
                    models.ManyToManyField(to="core.Ingredient"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="dish",
            name="cuisine",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.cuisine",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="cuisines",
            field=models.ManyToManyField(to="core.Cuisine"),
        ),
    ]
